//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppOddsMatcherUtility.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class matched_event
    {
        public int id { get; set; }
        public Nullable<System.DateTime> eventDate { get; set; }
        public string sport { get; set; }
        public string details { get; set; }
        public string betName { get; set; }
        public string marketName { get; set; }
        public Nullable<double> rating { get; set; }
        public string info { get; set; }
        public string bookmaker { get; set; }
        public Nullable<double> back { get; set; }
        public string exchange { get; set; }
        public Nullable<double> lay { get; set; }
        public Nullable<double> size { get; set; }
        public int betfairEventTypeId { get; set; }
        public string betfairMarketTypeCode { get; set; }
        public string competitionName { get; set; }
        public string countryCode { get; set; }
        public string timezone { get; set; }
        public long n { get; set; }
        public System.DateTime ut { get; set; }
        public string del { get; set; }
        public string bookmaker_name { get; set; }
        public string bookmaker_affiliate_link { get; set; }
    }
}
